#- name: Wipe Configuration
#  hosts: spine,leaf
#  become: yes
#  gather_facts: no
#  roles:
#  - reset

- name: Prespective Topplogy Manager
  hosts: spine,leaf
  become: yes
  gather_facts: no
  tasks:
  - name: Download the topology.dot file from the OOB-MGMT-SERVER
    get_url:
      url: http://192.168.0.254/topology.dot
      dest: /etc/ptm.d/topology.dot
      mode: 0755

  - name: Restart PTM Daemon to Apply new Topology.dot file
    service: name=ptmd state=restarted


- name: Configure CLAG on Leaf Switches
  hosts: leaf01:leaf02:leaf03:leaf04
  become: yes
  vars:
    devices:
        leaf01:
            loopback: "10.76.65.67/32"
            bgpasn: "65086"

        leaf02:
            loopback: "10.76.65.68/32"
            bgpasn: "65086"

        leaf03:
            loopback: "10.76.65.69/32"
            bgpasn: "65087"

        leaf04:
            loopback: "10.76.65.70/32"
            bgpasn: "65087"
  tasks:
  - name: Deploy Configuration To All Leafs
    nclu:
        commit: true
        description: "Deploy BGP configuration"
        commands:
            - add loopback lo ip address {{ devices[ansible_hostname].loopback }}
            - add bgp autonomous-system {{ devices[ansible_hostname].bgpasn }}
            - add bgp neighbor swp51 remote-as external
            - add bgp neighbor swp52 remote-as external
            - add bgp neighbor swp49 remote-as internal
            - add bgp neighbor swp50 remote-as internal
            - add bgp network {{ devices[ansible_hostname].loopback }}
            - add bgp bestpath as-path multipath-relax

- name: Configure Spines
  hosts: spine
  become: yes
  vars:
    devices:
        spine01:
            loopback: "10.76.65.65/32"
            bgpasn: "65085"
        spine02:
            loopback: "10.76.65.66/32"
            bgpasn: "65085"
  tasks:

  - name: Deploy Configuration to All Spines
    nclu:
        commit: true
        description: "Deploy interface configuration"
        commands:
            - add loopback lo ip address {{ devices[ansible_hostname].loopback }}
            - add bgp autonomous-system {{ devices[ansible_hostname].bgpasn }}
            - add bgp neighbor swp1 remote-as external
            - add bgp neighbor swp2 remote-as external
            - add bgp neighbor swp3 remote-as external
            - add bgp neighbor swp4 remote-as external
            - add bgp network {{ devices[ansible_hostname].loopback }}
            - add bgp bestpath as-path multipath-relax

  - name: Restart Networking
    service: name=networking state=restarted