---


- name: BACKUP PORTS.CONF
  fetch: dest=backup/"{{ lookup('pipe', 'date +%d%m%Y') }}"/{{inventory_hostname}}-"{{ lookup('pipe', 'date +%d%m%Y-%H-%M') }}"/ports.conf
         src=/etc/cumulus/ports.conf flat=yes

- name: BAKCUP INTERFACE FILE
  fetch: dest=backup/"{{ lookup('pipe', 'date +%d%m%Y') }}"/{{inventory_hostname}}-"{{ lookup('pipe', 'date +%d%m%Y-%H-%M') }}"/interfaces
         src=/etc/network/interfaces flat=yes

- name: BACKUP INTERFACES_CONFIG FILE
  fetch: dest=backup/"{{ lookup('pipe', 'date +%d%m%Y') }}"/{{inventory_hostname}}-"{{ lookup('pipe', 'date +%d%m%Y-%H-%M') }}"/interfaces_config
         src=/etc/network/interfaces flat=yes

- name: BACKUP FRR DAEMONS FILE
  fetch: dest=backup/"{{ lookup('pipe', 'date +%d%m%Y') }}"/{{inventory_hostname}}-"{{ lookup('pipe', 'date +%d%m%Y-%H-%M') }}"/daemons
         src=/etc/frr/daemons flat=yes

- name: BACKUP FRR.CONF
  fetch: dest=backup/"{{ lookup('pipe', 'date +%d%m%Y') }}"/{{inventory_hostname}}-"{{ lookup('pipe', 'date +%d%m%Y-%H-%M') }}"/frr.conf
         src=/etc/frr/frr.conf flat=yes