---


- name: GATHER BGP INFO IN JSON
  command: netq check bgp json
  register: result
  run_once: true
  failed_when: "'ERROR' in result.stdout"

- name: STDOUT STRING INTO JSON
  set_fact: json_output="{{result.stdout | from_json }}"
  run_once: true

- name: OUTPUT OF "json_output" VARIABLE
  debug: var=json_output
  run_once: true

- name: CHECK FAILED BGP MEMBERS
  debug: msg="Check failed bgp members"
  when: json_output["failedNodes"]|length == 0
  run_once: true

- name: BGP MEMBER FAILIAR RESAON
  fail: msg="Device {{item['hostname']}},
            Why node is in failed state? {{item['reason']}}"
  with_items: "{{json_output['failedNodes']}}"
  run_once: true
  ignore_errors: yes