#---
- name: VERIFY FRR RUNNING
  service: name=frr enabled=yes state=started

- name: CONFIGURE FRR DAEMON SETTINGS
  template: src=templates/daemons dest=/etc/frr/daemons
  notify: reload frr

- name: REDBER FRR CONFIGURATION
  local_action: template src="roles/routing/templates/frr.j2" dest="render/{{ inventory_hostname }}-frr_config"

- name: WRITE THE FRR CONFIGURATIION FILE
  template: src=templates/frr.j2 dest=/etc/frr/frr.conf
  notify:
    - reload frr
#    - restart netq agent
