---

loopback: 10.75.65.65/32

mgmt: 10.76.35.1/23

bgp_fabric:
  asn: 65085
  router_id: 10.75.65.65
  neighbor:
    - swp1
    - swp2
    - swp3
    - swp4
  networks:
    - 10.75.65.65/32
  evpn: true

interfaces:
  swp1:
    alias: link-lf-1
    mtu: 9216

  swp2:
    alias: link-lf-2
    mtu: 9216

  swp3:
    alias: link-lf-3
    mtu: 9216

  swp4:
    alias: link-lf-4
    mtu: 9216